---

- name: send sse file to mds
  synchronize:
    src: "{{ local_path_mds_home_sse_colodir }}/"
    dest: "{{ slave_path_mds_home_data_exchange }}/"
    checksum: yes
  register: collector_sse_files_result
  ignore_errors: yes
