---
- hosts: all

  vars_files:
    - ../common/base_vars.yml

  tasks:
    - name: start mon with Java environment
      shell: |
        export JAVA_HOME={{ java_home }}
        export PATH=$JAVA_HOME/bin:$PATH
        nohup sh start.sh > /dev/null 2>&1 &
      args:
        chdir: "{{ slave_path_mon_home }}"
      ignore_errors: True
      register: start_res
