---
- hosts: all

  vars_files:
    - ../common/base_vars.yaml

  tasks:
    - name: stop mds
      command: ./mds stop -F
      args:
        chdir: "{{ slave_path_mds_home_bin }}"

    - name: clear txlog
      file:
        path: "{{ slave_path_mds_home_txlog }}"
        state: absent

    - name: mkdir txlog dir
      file:
        path: "{{ slave_path_mds_home_txlog }}"
        state: directory

    - name: start master mds
      command: ./mds start
      args:
        chdir: "{{ slave_path_mds_home_bin }}"
      when: node_role == "master"
      ignore_errors: True
      register: start_master_res

    - name: start follow mds
      command: ./mds start
      args:
        chdir: "{{ slave_path_mds_home_bin }}"
      when: node_role != "master"
      ignore_errors: True
      register: start_follow_res
