---
- hosts: all

  vars_files:
    - ../common/base_vars.yml

  tasks:
    - name: stop mds
      command: ./mds stop -F
      args:
        chdir: "{{ slave_path_mds_home_bin }}"

    - name: start master mds
      command: ./mds start
      args:
        chdir: "{{ slave_path_mds_home_bin }}"
      when: node_role == "master"
      ignore_errors: True
      register: start_master_res

    - name: start follow mds
      command: ./mds start
      args:
        chdir: "{{ slave_path_mds_home_bin }}"
      when: node_role != "master"
      ignore_errors: True
      register: start_follow_res
