---
- hosts: all

  vars_files:
    - ../common/base_vars.yaml

  tasks:
    - name: nakedstart master mds
      command: ./mds st -B
      args:
        chdir: "{{ slave_path_mds_home_bin }}"
      when: node_role == "master"

    - name: nakedstart follow and arbiter mds
      command: ./mds st -B
      args:
        chdir: "{{ slave_path_mds_home_bin }}"
      when: node_role != "master"
