---

- hosts: all
  vars_files:
    - ../../common/base_vars.yml
    - ./csdc_vars.yml

  tasks:
    - include_tasks: ../../common/load_automatic.yml

    - include_tasks: ../before_playbook.yml

    - include_tasks: ./gateway_to_local.yml

    - include_tasks: ./local_to_oes.yml

    - include_tasks: ./csdc_checker.yml

    - include_tasks: ../after_playbook.yml
