---

- name: stop mds arbiter
  command: ./mds stop -F
  args:
    chdir: "{{ slave_path_mds_home_bin }}"
  when: node_role == "arbiter"

- name: start arbiter mds
  command: ./mds start
  args:
    chdir: "{{ slave_path_mds_home_bin }}"
  when: node_role == "arbiter"
