###################### local工作目录相关文件位置 ####################
local_path_mon_home_config: "{{ local_path_mon_home }}/config"
local_path_mon_home_config_colodir: "{{ local_path_mon_home_config }}/{{ colony_num }}"
local_path_mon_home_flag: "{{ local_path_mon_home }}/flags"
local_path_mon_home_flag_colodir: "{{ local_path_mon_home_flag }}/{{ colony_num }}"
local_path_mon_home_backup: "{{ local_path_mon_home }}/backup"
local_path_mon_home_backup_colodir: "{{ local_path_mon_home_backup }}/{{ colony_num }}"
local_path_mon_home_tmp: "{{ local_path_mon_home }}/.tmp"
local_path_mon_home_tmp_colodir: "{{ local_path_mon_home_tmp }}/{{ colony_num }}"
###################### local工作目录相关文件位置 ####################

##################### 被控机相关目录 ##############################
slave_path_mon_home: ""
slave_path_mon_home_art: "{{ slave_path_mon_home }}/art"
slave_path_mon_home_config: "{{ slave_path_mon_home }}/config"
slave_path_mon_home_database: "{{ slave_path_mon_home }}/database"
slave_backup_path: "{{ ansible_env.HOME }}/mon_bak"
##################### 被控机相关目录 ##############################
