###################### local工作目录相关文件位置 ####################
local_path_oes_home_bin: "{{ local_path_oes_home }}/bin"
local_path_oes_home_bin_colodir: "{{ local_path_oes_home_bin }}/{{ colony_num }}"
local_path_oes_home_config: "{{ local_path_oes_home }}/config"
local_path_oes_home_config_all: "{{ local_path_oes_home_config }}/{{ colony_num }}/all"
local_path_oes_home_config_specdir: "{{ local_path_oes_home_config }}/{{ colony_num }}/{{ specdir }}"
local_path_oes_home_flag: "{{ local_path_oes_home }}/flags"
local_path_oes_home_flag_colodir: "{{ local_path_oes_home_flag }}/{{ colony_num }}"
local_path_oes_home_backup: "{{ local_path_oes_home }}/backup"
local_path_oes_home_backup_colodir: "{{ local_path_oes_home_backup }}/{{ colony_num }}"
local_path_oes_home_tmp: "{{ local_path_oes_home }}/.tmp"
local_path_oes_home_tmp_colodir: "{{ local_path_oes_home_tmp }}/{{ colony_num }}"
local_path_oes_home_mon: "{{ local_path_oes_home }}/mon"
local_path_oes_home_mon_colodir: "{{ local_path_oes_home_mon }}/{{ colony_num }}"
local_path_oes_home_counter: "{{ local_path_oes_home }}/counter"
local_path_oes_home_counter_colodir: "{{ local_path_oes_home_counter }}/{{ colony_num }}"
local_path_oes_home_counter_colodir_bin: "{{ local_path_oes_home_counter_colodir }}/bin"
local_path_oes_home_counter_colodir_bin_script: "{{ local_path_oes_home_counter_colodir_bin }}/script"
local_path_oes_home_counter_colodir_bin_lib: "{{ local_path_oes_home_counter_colodir_bin }}/lib"
local_path_oes_home_counter_colodir_conf: "{{ local_path_oes_home_counter_colodir }}/conf"
local_path_oes_home_counter_colodir_logs: "{{ local_path_oes_home_counter_colodir }}/logs"
local_path_oes_home_counter_colodir_data: "{{ local_path_oes_home_counter_colodir }}/data"
local_path_oes_home_counter_colodir_data_broker: "{{ local_path_oes_home_counter_colodir_data }}/broker"
local_path_oes_home_counter_colodir_data_exchange: "{{ local_path_oes_home_counter_colodir_data }}/exchange"
local_path_oes_home_counter_colodir_default: "{{ local_path_oes_home_counter_colodir }}/default"
local_path_oes_home_bse: "{{ local_path_oes_home }}/bse"
local_path_oes_home_bse_colodir: "{{ local_path_oes_home_bse }}/{{ colony_num }}"
local_path_oes_home_sse: "{{ local_path_oes_home }}/sse"
local_path_oes_home_sse_colodir: "{{ local_path_oes_home_sse }}/{{ colony_num }}"
local_path_oes_home_sse_etf: "{{ local_path_oes_home }}/sse_etf"
local_path_oes_home_sse_etf_colodir: "{{ local_path_oes_home_sse_etf }}/{{ colony_num }}"
local_path_oes_home_sse_late: "{{ local_path_oes_home }}/sse_late"
local_path_oes_home_sse_late_colodir: "{{ local_path_oes_home_sse_late }}/{{ colony_num }}"
local_path_oes_home_szse: "{{ local_path_oes_home }}/szse"
local_path_oes_home_szse_colodir: "{{ local_path_oes_home_szse }}/{{ colony_num }}"
local_path_oes_home_szse_etf: "{{ local_path_oes_home }}/szse_etf"
local_path_oes_home_szse_etf_colodir: "{{ local_path_oes_home_szse_etf }}/{{ colony_num }}"
local_path_oes_home_szse_late: "{{ local_path_oes_home }}/szse_late"
local_path_oes_home_szse_late_colodir: "{{ local_path_oes_home_szse_late }}/{{ colony_num }}"
local_path_oes_home_csdc: "{{ local_path_oes_home }}/csdc"
local_path_oes_home_csdc_colodir: "{{ local_path_oes_home_csdc }}/{{ colony_num }}"

local_path_script_home_python: "{{ local_path_script_home }}/python"
local_path_script_home_dep: "{{ local_path_script_home }}/dep"
local_path_script_home_cmd: "{{ local_path_script_home }}/cmd"
local_path_script_home_control: "{{ local_path_script_home }}/control"
local_path_script_home_emergency: "{{ local_path_script_home }}/emergency"
local_path_script_home_slave: "{{ local_path_script_home }}/slave"
###################### local工作目录相关文件位置 ####################

default_counter_files2: ['PrivateFundBlacklist.csv', 'PrivateFundInfo.csv', 'PrivateFundTradeAccounts.csv']

#################被控机相关目录######################################
slave_path_user_home: "/home/{{ ansible_user }}/{{ specdir }}"
slave_path_oes_home: "{{ slave_path_user_home }}/{{ pkg_name }}"
slave_path_oes_home_art: "{{ slave_path_oes_home }}/art"
slave_path_oes_home_bin: "{{ slave_path_oes_home }}/bin"
slave_path_oes_home_bin_lib: "{{ slave_path_oes_home }}/bin/lib"
slave_path_oes_home_bin_script: "{{ slave_path_oes_home }}/bin/script"
slave_path_oes_home_sbin: "{{ slave_path_oes_home }}/sbin"
slave_path_oes_home_conf: "{{ slave_path_oes_home }}/conf"
slave_path_oes_home_data: "{{ slave_path_oes_home }}/data"
slave_path_oes_home_txlog: "{{ slave_path_oes_home }}/txlog"
slave_path_oes_home_logs: "{{ slave_path_oes_home }}/logs"
slave_path_oes_home_data_flags: "{{ slave_path_oes_home_data }}/flags"
slave_path_oes_home_data_broker: "{{ slave_path_oes_home_data }}/broker"
slave_path_oes_home_data_monitor: "{{ slave_path_oes_home_data }}/monitor"
slave_path_oes_home_data_csdc: "{{ slave_path_oes_home_data }}/exchange"
slave_path_oes_home_data_exchange: "{{ slave_path_oes_home_data }}/exchange"
slave_path_oes_home_data_exchange_sse_etf: "{{ slave_path_oes_home_data_exchange }}/sse_etf"
slave_path_oes_home_data_exchange_szse_etf: "{{ slave_path_oes_home_data_exchange }}/szse_etf"

slave_backup_path: "{{ slave_path_user_home }}/backup"
slave_backup_path_oes: "{{ slave_backup_path }}/{{ pkg_name }}"
slave_backup_path_oes_curr_date: "{{ slave_backup_path_oes }}/{{ curr_date }}"
#################被控机相关目录#######################################


############################## flag 文件名 ##########################
fetch_mon_ok: "DATA_FETCH_MON.{{ curr_date }}.OK"
fetch_counter_ok: "DATA_FETCH_COUNTER.{{ curr_date }}.OK"
fetch_sse_ok: "DATA_FETCH_SSE.{{ curr_date }}.OK"
fetch_szse_ok: "DATA_FETCH_SZSE.{{ curr_date }}.OK"
fetch_csdc_ok: "DATA_FETCH_SDC.{{ curr_date }}.OK"
fetch_sse_late_ok: "DATA_FETCH_SSE_LATE.{{ curr_date }}.OK"
fetch_szse_late_ok: "DATA_FETCH_SZSE_LATE.{{ curr_date }}.OK"

xcounter_run_fetch_ok: "XCOUNTER.{{ curr_date }}.OK"
xcounter_run_freezed_ok: "TRANSFER.{{ curr_date }}.OK"

flag_name: "{{ cron_job_name }}_{{ curr_date }}"
flag_success: "{{ flag_name }}.success"
flag_failed: "{{ flag_name }}.failed"
flag_running: "{{ flag_name }}.running"
flag_timeout: "{{ flag_name }}.timeout"
flag_cancel: "{{ flag_name }}.cancel"
flag_crash: "{{ flag_name }}.crash"
#####################################################################
