################ mds计划任务 #######################
# 本配置仅用于创建mds集群时自动注册的计划任务时间
# 计划任务实际注册时间以数据库为准
mds:  
  - mon: "30 6 * * 1-5"
  - bse: "2 8 * * 1-5"
  - sse: "5 8 * * 1-5"
  - szse: "36 7 * * 1-5"
  - backup: "0 20 * * 1-5"
################ mds计划任务() #######################

################ stk计划任务 #######################
# 本配置仅用于创建stk集群时自动注册的计划任务时间
# 计划任务实际注册时间以数据库为准
stk: 
  - mon: "30 6 * * 1-5"
  - counter_fetch: "30 7 * * 1-5"
  - counter_distribute: "40 7 * * 1-5"
  - bse: "2 8 * * 1-5"
  - sse: "5 8 * * 1-5"
  - szse: "36 7 * * 1-5"
  - csdc: "35 7 * * 1-5"
  - backup: "0 20 * * 1-5"
################ stk计划任务 #######################

################ crd计划任务 #######################
# 本配置仅用于创建crd集群时自动注册的计划任务时间
# 计划任务实际注册时间以数据库为准
crd: 
  - mon: "30 6 * * 1-5"
  - counter_fetch: "30 7 * * 1-5"
  - counter_distribute: "40 7 * * 1-5"
  - sse: "5 8 * * 1-5"
  - szse: "36 7 * * 1-5"
  - csdc: "35 7 * * 1-5"
  - sse_late: "40 8 * * 1-5"
  - szse_late: "40 8 * * 1-5"
  - backup: "0 20 * * 1-5"
################ crd计划任务 #######################

################ opt计划任务 #######################
# 本配置仅用于创建opt集群时自动注册的计划任务时间
# 计划任务实际注册时间以数据库为准
opt:  
  - mon: "30 6 * * 1-5"
  - counter_fetch: "30 7 * * 1-5"
  - counter_distribute: "40 7 * * 1-5"
  - sse: "5 8 * * 1-5"
  - szse: "36 7 * * 1-5"
  - backup: "0 20 * * 1-5"
################ opt计划任务 #######################
