---
- hosts: all

  vars_files:
    - ../../common/base_vars.yaml
    - ./backup_vars.yaml

  tasks:
    - include_tasks: ../../common/load_automatic.yaml

    - include_tasks: ../before_playbook.yaml

    - include_tasks: ./mds_backup.yaml

    - include_tasks: ./after_playbook.yaml
