---

- hosts: all
  vars_files:
    - ../../common/base_vars.yaml
    - ./mon_vars.yaml

  tasks:
    - include_tasks: ../../common/load_automatic.yaml

    - include_tasks: ../before_playbook.yaml

    - include_tasks: ./gateway_to_local.yaml

    - include_tasks: ./local_to_oes.yaml

    - include_tasks: ./mon_checker.yaml

    - include_tasks: ./crd_personalization.yaml
      when: system_type == "crd"

    - include_tasks: ../after_playbook.yaml
