---
- hosts: all

  vars_files:
    - ../common/base_vars.yml

  tasks:
    - name: check .ok file in salve
      wait_for:
        path: "{{ slave_path_oes_home_data_flags }}/{{ item }}"
        state: present
        timeout: 1
      with_items:
        - "{{ fetch_sse_ok }}"
        - "{{ fetch_szse_ok }}"
        - "{{ fetch_mon_ok }}"

    - name: load_data
      command: ./oes load -D -N
      args:
        chdir: "{{ slave_path_oes_home_bin }}"
