---
- hosts: all

  vars_files:
    - ../common/base_vars.yaml

  tasks:
    - name: nakedstart master oes
      command: ./oes st -B
      args:
        chdir: "{{ slave_path_oes_home_bin }}"
      when: node_role == "master"

    - name: nakedstart follow and arbiter oes
      command: ./oes st -B
      args:
        chdir: "{{ slave_path_oes_home_bin }}"
      when: node_role != "master"
