---
- hosts: all

  vars_files:
    - ../common/base_vars.yml

  tasks:
    - include_tasks: ../common/load_automatic.yml
  
    - name: transfer2oes thaw
      raw: 'cd {{ local_path_oes_home_counter_colodir_bin_script }} &&
            export LD_LIBRARY_PATH=$PWD:$PWD/../lib &&
            {{ local_python_interpreter }} $PWD/xcounter2oes_transfer2counter_main.py {{ counter_thaw_cmd_args }} 2> xcounter2oes_transfer2counter_main.log'
      delegate_to: 127.0.0.1
      run_once: true
