---

- name: stop oes follow
  command: ./oes stop -F
  args:
    chdir: "{{ slave_path_oes_home_bin }}"
  when: node_role == "follow"

- name: find follow txlog files
  find:
    paths: "{{ slave_path_oes_home_txlog }}"
    patterns: "TXLOG_*"
  register: txlog_files
  when: node_role == "follow"

- name: clear follow txlog files
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ txlog_files.files | map(attribute='path') | list }}"
  when: node_role == "follow"

- name: archive oes master data
  archive:
    path: "{{ slave_path_oes_home_data }}"
    dest: "{{ slave_path_oes_home }}/data.tar.gz"
  when: node_role == "master"

- name: fetch oes master data to local
  fetch:
    src: "{{ slave_path_oes_home }}/data.tar.gz"
    dest: "{{ local_path_oes_home_tmp_colodir }}/data.tar.gz"
    flat: "yes"
  when: node_role == "master"

- name: clear oes master data tar file
  file:
    path: "{{ slave_path_oes_home_data }}/data.tar.gz"
    state: absent
  when: node_role == "master"

- name: copy archived file to target remote host
  copy:
    src: "{{ local_path_oes_home_tmp_colodir }}/data.tar.gz"
    dest: "{{ slave_path_oes_home }}/data.tar.gz"
    force: "yes"
  when: node_role == "follow"

- name: unarchived data tar file
  unarchive:
    src: "{{ slave_path_oes_home }}/data.tar.gz"
    dest: "{{ slave_path_oes_home_data }}"
    remote_src: "yes"
  when: node_role == "follow"

- name: clear txlog tar files
  file:
    path: "{{ slave_path_oes_home }}/data.tar.gz"
    state: absent

- name: start oes follow
  command: ./oes start
  args:
    chdir: "{{ slave_path_oes_home_bin }}"
  when: node_role == "follow"
  
